version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2404:current

    steps:
      - checkout
      - run: wget -qO- https://api.wodby.com/v1/get/cli | sh
      - run: wodby ci init $WODBY_APP_SERVICE_ID
      - run: wodby ci build rails -f Dockerfile
      - run: wodby ci release
      - run: wodby ci deploy
