version: 2.1

orbs:
  wodby: wodby/setup-wodby-cli@1

jobs:
  build:
    machine:
      image: ubuntu-2604:current

    steps:
      - checkout
      - wodby/setup:
          app-service-id: $WODBY_APP_SERVICE_ID

      - run:
          name: Run tests
          command: wodby ci run -s go -- go test ./...

      - run: wodby ci build go -f Dockerfile
      - run: wodby ci release
      - run: wodby ci deploy
