version: 0.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    steps:
      - clone
      - run: wodby ci init $WODBY_BUILD_ID
      - run: wodby ci run -s go -- go test ./...
      - run: wodby ci build go -f Dockerfile
      - run: wodby ci release
      - run: wodby ci deploy
