version: 0.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    steps:
      - clone

      - cache_restore:
          path: ~/.composer
          key: 'composer-{{ hash "composer.lock" }}-v1'

      - run: wget -qO- https://api.wodby.com/v1/get/cli | sh
      - run: wodby ci init $WODBY_BUILD_ID
      - run: wodby ci run -v $HOME/.composer:/home/wodby/.composer -- composer install -n --no-ansi

      - cache_save:
          key: 'composer-{{ hash "composer.lock" }}-v1'
          path: ~/.composer

      - run: wodby ci build
#      - run: wodby ci build nginx --from static --to /var/www/html/static        
      - run: wodby ci release
      - run: wodby ci deploy
