version: 0.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    steps:
      - clone

      - cache_restore:
          path: ~/.composer/cache
          key: 'composer-{{ hash "composer.lock" }}-v1'

      - run: wodby ci init $WODBY_BUILD_ID
      - run: wodby ci run -- composer install --prefer-dist -n --no-ansi

      - cache_save:
          key: 'composer-{{ hash "composer.lock" }}-v1'
          path: ~/.composer/cache

      - run: wodby ci build
      # To copy only a static subdirectory into Nginx:
      # - run: wodby ci build nginx --from static --to /var/www/html/static
      - run: wodby ci release
      - run: wodby ci deploy
