version: 0.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    steps:
      - clone

      - cache_restore:
          path: ~/.composer
          key: 'composer-{{ hash "composer.lock" }}-v1'

      - run: wodby ci init $WODBY_BUILD_ID
      - run: wodby ci run -v $HOME/.composer:/home/wodby/.composer -s matomo -- composer install --prefer-dist -n --no-ansi

      - cache_save:
          key: 'composer-{{ hash "composer.lock" }}-v1'
          path: ~/.composer

      - run: wodby ci build
      - run: wodby ci release
      - run: wodby ci deploy
