version: 0.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    steps:
      - clone

      - cache_restore:
          path: ~/.npm
          key: 'npm-{{ hash "package-lock.json" }}-v1'

      - run: wodby ci init $WODBY_BUILD_ID
      - run: wodby ci run -v $HOME/.npm:/home/node/.npm -s nextjs -- npm ci

      - cache_save:
          key: 'npm-{{ hash "package-lock.json" }}-v1'
          path: ~/.npm

      - run: wodby ci build nextjs -f Dockerfile
      - run: wodby ci release
      - run: wodby ci deploy
