name: Build

on:
  push:
    branches:
      - 'main'

    tags:
      - '*'

  pull_request:

env:
  APP_INSTANCE_ID: MY-APP-INSTANCE-ID
  WODBY_API_KEY: ${{ secrets.WODBY_API_KEY }}
  BUILD_STANDALONE: 'true'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Install node modules
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        run: |
          set -ex
          
          wget -qO- "https://api.wodby.com/api/v1/get/cli" | sh
          
          wodby ci init ${{ env.APP_INSTANCE_ID }}
          wodby ci build node --dockerfile Dockerfile 
          wodby ci release
          wodby ci deploy
