# The following example
# 1. Installs your dependencies from composer.json
# 2. Builds and pushes default images with contents of the current directory (./)
# 3. Deploys build to your app instance

image: wodby/wodby-cli

options:
  docker: true

pipelines:
  default:
    - step:
        caches:
          - docker
          - composer
        script:
          - wodby ci init $WODBY_INSTANCE_UUID
          - wodby ci run -v $HOME/.composer:$HOME/.composer -- composer install --prefer-dist -n --no-dev
          - wodby ci build --from ./
          - wodby ci release
          - wodby ci deploy
