# The following example
# 1. Installs your dependencies from composer.json
# 2. Builds and pushes default images with contents of the current directory (./)
# 3. Deploys build to your app instance

version: 2

jobs:
  build:
    machine: 
      # Manually specify newer image because the default one has expired root certificates.
      image: circleci/classic:201808-01

    steps:
      - checkout

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-

      - run: wget -qO- https://api.wodby.com/api/v1/get/cli | sh
      - run: wodby ci init $WODBY_INSTANCE_UUID
      - run:
          name: Fix .composer permissions
          command: wodby ci run -v $HOME/.composer:/home/wodby/.composer --user root -- chown -R 1000:1000 /home/wodby/.composer

      - run: 
          name: Install composer dependencies
          command: wodby ci run -v $HOME/.composer:/home/wodby/.composer -s php -- composer install -n

## When you need to use a checkout key for private repositories:
#       - run: 
#           name: Install composer dependencies with private packages
#           command: wodby ci run \
#             -v /home/circleci/.ssh/known_hosts:/home/wodby/.ssh/known_hosts \
#             -v /home/circleci/.ssh/id_rsa_[your-checkout-key-fingerprint]:/home/wodby/.ssh/id_rsa \
#             -v $HOME/.composer:/home/wodby/.composer \
#             -s php -- composer install -n

      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - ~/.composer

      - run: wodby ci build --from ./
      - run: wodby ci release
      - run: wodby ci deploy
